Migrate away from Eq1 / Ord1 / Show1
spell-music/data-fix pull request #28
Opened 2024-02-24 23:50 UTC by Bodigrim

Closes #27. 

Tested with 
```
packages: .
packages: dhall-1.42.1
packages: aeson-2.2.1.0
packages: hnix-0.17.0
packages: sexp-grammar-2.3.4.2
packages: recursion-schemes-5.2.2.5
packages: quickcheck-instances-0.3.30
packages: liquidhaskell-boot-0.9.8.1

allow-newer: hnix:aeson, hnix:free, hnix:bytestring, hnix-store-core:algebraic-graphs
```

I'm on aarch64 so unfortunately cannot test locally with old GHCs. 

Really old GHC <= 7.6 fail in CI. If we must retain compatibility with them, I can revert changes with regards to `Typeable1`.

2024-03-23 00:55 UTC, Bodigrim commented
@phadej I got access to a x86_64 machine and tested the patch with GHC 8.4 and 8.6. No breakage in downstream packages detected.

2024-04-20 16:11 UTC, Bodigrim commented
@phadej anything else you would like me to check here?

2024-04-20 17:56 UTC, phadej commented
Everything looks fine.

I'm waiting for GHC-9.10 release; as this is still a breaking change, I'd like to make a 9.10 compatibility work first, and only then make a major release.

2024-04-23 14:58 UTC, phadej requested changes

2024-04-23 14:58 UTC, phadej commented on src/Data/Fix.hs
> +instance (Functor f, Ord (f (Fix f))) => Ord (Mu f) where
Now thinking more about it. I'm not happy about this change. It exposes too much of implementation detail to the surface. `Ord1 f` is asking for more, but doesn't tell anyone on the outside that `Fix` is used internally.

I'm not particularly happy with this. So I'm sorry, but we'll need to rethink this change.

Changing `Fix` interface is one option, but I don't like that either, as then `Fix` and `Mu/Nu` parts will look different.

2024-04-23 14:59 UTC, phadej commented
One option, which is not breaking, and may fix part of #77 is to use `forall a. Ord a => Ord (f a)` implied by `Ord1 f` in the implementation, when such implication exists (i.e. more recent `base`).

2024-04-23 19:39 UTC, Bodigrim commented
> One option, which is not breaking, and may fix part of #27 is to use `forall a. Ord a => Ord (f a)` implied by `Ord1 f` in the implementation, when such implication exists (i.e. more recent `base`).

Works for me. Do you want it only for `Mu` and `Nu` or for `Fix` also? Shall I update the PR?

2024-07-04 20:07 UTC, closed without merging

2024-07-04 20:07 UTC, Bodigrim commented
Closing in favor of #29.